### ISSUE TITLE
Missing L0 files from 20230627

### ISSUE THREAD

**Issue by RussLaher** [Keck-DataReductionPipelines/KPF-Pipeline#702]
There were 531 L0 files for 20230627 registered in the pipeline-operations database on 2023-06-27, but now they are missing from disk.  I am creating this ticket to bring this to your attention.

kpfopsdb=> select count(*) from l0files where filename like '%20230627%';

count
531

[rlaher@shrek ~]$ ls /data/kpf/L0/20230627/*fits
ls: cannot access /data/kpf/L0/20230627/*fits: No such file or directory

kpfopsdb=> select created,filename from l0files where filename like '%20230627%' order by created;

 created                                    |                    filename                     
2023-06-27 17:45:09.057274 | /data/kpf/L0/20230627/KP.20230627.03275.67.fits
2023-06-27 17:45:12.054421 | /data/kpf/L0/20230627/KP.20230627.00071.13.fits
2023-06-27 17:45:14.420411 | /data/kpf/L0/20230627/KP.20230627.03225.01.fits
.
.
.
2023-06-27 18:10:40.896859 | /data/kpf/L0/20230627/KP.20230627.86226.71.fits
2023-06-27 18:10:43.564456 | /data/kpf/L0/20230627/KP.20230627.86308.14.fits
2023-06-27 18:10:46.265682 | /data/kpf/L0/20230627/KP.20230627.86389.63.fits
(531 rows)

**Comment by awhoward** [comment]
We were on-sky that night, so we need to find the L0 files.

They are also missing from `/backup/backup-shrek/data/kpf/L0/20230627`.

We should have other copies of the data, on BackBlaze, KOA, and maybe on the WMKO servers.   Looking on the WMKO servers, I see this:
```
kpf:/s/sdata1701/kpfeng/2023jun26> ls
CRED2  FVC1  FVC2  FVC3  L0  new_L0
```
There are a zillion files in the `L0` directory, but no .fits fits files in the `new_L0` directory.  Howard, could you check to see if this is one of the dates that Brad Holden had to regenerate L0 files for?  This will require some Slack digging.

**Comment by bpholden** [comment]
There was a l0_assemble.out file which simply logged the creation of a
number of files.
So there should have been new files made.
There are no green, red, or HK directories, so we cannot recreate the
updated L0 files.

Searching slack in kpf-testing on "jun26" shows:

The issue was that keyheader was not producing output, so the files are
missing keywords.
(There have been a number of times where I have found that old versions of
kpfassemble and l0_assemble were installed and running, which is not
supposed to happen.)
I restarted the assembler that day, but I "paused" the SoCal script which
caused it to stop (and not just pause.)

There is a note from Andrew saying that he would move the files to shrek.

**Comment by awhoward** [comment]
Thanks for that, @bpholden.  I'd forgotten about promising to copy the files.

I think we're still missing some files, at least on the WMKO servers.  The directory `/s/sdata1701/kpfeng/2023jun26/new_L0` referenced in Slack that should contain updated L0 files is empty.  I'm not sure if this because of regular file culling or other reasons.  The directory `/s/sdata1701/kpfeng/2023jun26/L0` contains L0 files from SoCal spanning `KP.20230627.70076.22.fits` to `KP.20230627.74990.71.fits`, but the attached Grafana screenshot with UTC timestamps shows that KPF was active all day, not just at the end of the day as those filenames would suggest.  (Note that `KP.20230627.xxx` files are stored in `2023jun26` because of the HST/UTC difference and when directories are created.)

The missing data includes a full night of on-sky time so there's a high priority for recovery.

![grafana_UTD20230627](https://github.com/Keck-DataReductionPipelines/KPF-Pipeline/assets/16376935/96bf05b5-d0dc-4d8e-80ee-a6860c8a8683)

**Comment by awhoward** [comment]
Joel Ong (Hawaii) was the PI that night.  We may need to contact him to get access to the non-calibration data taken through CPS on HST 6/26/2023.  Note that the observations are mostly not his because it was a CPS queue night.

**Comment by awhoward** [comment]
I take it back. Most, but not all, of the on-sky observations are for Joel's program, which was an obliquity measurement.

**Comment by awhoward** [comment]
@howardisaacson -- this is complete, right?

**Comment by howardisaacson** [comment]
Correct, and the corrected data made it into the Keck Archive.
