### ISSUE TITLE
"Sci Fiber" Keyword incorrect UT:2Mar2024

### ISSUE THREAD

**Issue by howardisaacson** [Keck-DataReductionPipelines/KPF-Pipeline#828]
On a second-half science night, UT: March 2nd, 2024, the "Sci Fiber" keyword is not populated correctly. It should be "Target", but is instead "None".   This keyword may be used to distinguish on-sky observations from calibrations. If possible, we should update the header keyword.  I checked back to August 1 2023 and this was the only night that this happened.

**Comment by awhoward** [comment]
Let's consider putting fixed L0 files into KOA.

**Comment by bpholden** [comment]
I have looked into the keyword database for this night. The value of the
keyword that is written into the header was "None." This was not a problem
with the assembler.

The configuration software reported the correct value as well. The FIU
reported that no light was coming through the AO system because the hatch
was closed.
This is obviously an error, and I can report the issue to Kyle who is in
charge of the FIU software.

**Comment by bpholden** [comment]
I corresponded with Kyle Lanclos and he said that the AO hatch was broken
that night and so had to be manually opened.
This led to the incorrect telemetry.

**Comment by howardisaacson** [comment]
The data has been correct in the KOA. The 'SCI-OBJ'  now reads: 'Target'. 
The data is staged on cadence and ready to copy to shrek and overwrite previous data.
I plan on copying only science data from that date, not calibration data, although both are available.

**Comment by howardisaacson** [comment]
Thank you for your help with this. The corrected data is now both in the KOA and downloaded by CPS. Along with SCI-OBJ keyword, which was none and is now 'Target', the program name was corrected from engineering to the proper PI on that night.
